function plotprp(X1, YMatrix1,eq,ty,i,yl)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Aug-2013 15:04:17

% Create figure
figure1 = figure('Name',strcat('phi = ',eq));

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1(:,1),YMatrix1(:,1),'-bs','MarkerFaceColor','b','MarkerSize',5,'Parent',axes1);
plot2 = plot(X1(:,2),YMatrix1(:,2),'-gv','MarkerFaceColor','g','MarkerSize',5,'Parent',axes1);
plot3 = plot(X1(:,3),YMatrix1(:,3),'-ro','MarkerFaceColor','r','MarkerSize',5,'Parent',axes1);


set(plot1,'DisplayName',strcat(ty,'1'));
set(plot2,'DisplayName',strcat(ty,'2'));
set(plot3,'DisplayName',strcat(ty,'3'));
hold on;




% Create xlabel
xlabel('Cycle Number');

% Create ylabel
ylabel(yl);

% Create title
title({strcat('\phi = 1.00',';P_i_n = 10') });

% Create legend
legend(axes1,'show');

 saveas(figure1,strcat(ty,'_',eq,'_',int2str(i),'.jpg'),'jpg');